name: Pre-release Python bridge

on: workflow_dispatch

env:
  PIPENV_PIPFILE: bridges/python/src
  PIPENV_VENV_IN_PROJECT: true

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.10

      - name: Install Pipenv
        run: pip install --upgrade pip && pip install pipenv==2022.7.24

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Set Python bridge version
        working-directory: bridges/python/src
        run: |
          echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV

      - name: Display Python bridge version
        run: |
          echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"

      - name: Install core
        run: npm ci

      - name: Set up Python bridge
        run: npm run setup:python-bridge

      - name: Build Python bridge
        run: npm run build:python-bridge

      - name: Upload Python bridge
        uses: actions/upload-artifact@v3
        with:
          path: bridges/python/dist/*.zip

  build-linux-aarch64:
    name: Build on Linux AArch64
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.10

      - name: Set Python bridge version
        working-directory: bridges/python/src
        run: |
          echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV

      - name: Display Python bridge version
        run: |
          echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands on AArch64
        with:
          arch: aarch64
          distro: ubuntu_latest

          githubToken: ${{ secrets.GITHUB_TOKEN }}

          run: |
            echo "Install Pipenv"
            pip install --upgrade pip && pip install pipenv==2022.7.24
            echo "Install core"
            npm ci
            echo "Set up Python bridge"
            npm run setup:python-bridge
            echo "Build Python bridge"
            npm run build:python-bridge

      - name: Upload Python bridge
        uses: actions/upload-artifact@v3
        with:
          path: bridges/python/dist/*.zip

  draft-release:
    name: Draft-release
    needs: [build, build-linux-aarch64]
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.10

      - name: Set Python bridge version
        working-directory: bridges/python/src
        run: |
          echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV

      - name: Download Python bridge
        uses: actions/download-artifact@v3
        with:
          path: bridges/python/dist

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: python-bridge_v${{ env.PYTHON_BRIDGE_VERSION }}
          draft: true
          prerelease: false
          title: Python Bridge ${{ env.PYTHON_BRIDGE_VERSION }}
          files: bridges/python/dist/artifact/*.zip
